package dev.burgerman.bitelo.model.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Request DTO for verifying a TOTP (Time-based One-Time Password) code.")
public record VerifyTOTPRequest(

        @Schema(description = "TOTP code generated by the user's google authenticator app.", example = "123456")
        String code
) {}
